version: '3.6'
services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "446:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: '-s "Mount;/mnt" -s "BobDrive;/mnt;yes;no;no;bob" -u "bob;bobspasswd" -p'
  
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    networks:
      - default
    ports: 
      - 1972
      - 52795:52773
      - 53773
    volumes:
      - ./:/irisdev/app

networks:
  default: